x-environment: &default-environment
    DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
    SECRET_KEY: ${SECRET_KEY}
    PORT: 8003
    GLITCHTIP_BASE_URL: ${GLITCHTIP_BASE_URL}
    GLITCHTIP_DOMAIN: ${GLITCHTIP_BASE_URL}
    EMAIL_URL: ${EMAIL_URL}
    DEFAULT_FROM_EMAIL: ${DEFAULT_FROM_EMAIL}
    ENABLE_OPEN_USER_REGISTRATION: "True"

x-depends_on: &default-depends_on
    - postgres
    - redis

services:
    migrate:
        image: glitchtip/glitchtip:latest
        depends_on: *default-depends_on
        command: "./manage.py migrate"
        environment: *default-environment
    postgres:
        image: postgres:14
        environment:
            POSTGRES_HOST_AUTH_METHOD: "trust"
        restart: unless-stopped
        volumes:
            # This will save the PostgreSQL data in your current folder
            - pg_data:/var/lib/postgresql/data
    redis:
        image: redis
        restart: unless-stopped
    # smtp:
    #     # TODO: https://github.com/namshi/docker-smtp
    #     image: namshi/smtp
    #     restart: unless-stopped
    #     expose:
    #         - "25"
    #     environment:
    #         GMAIL_USER: ${GMAIL_USER}
    #         GMAIL_PASSWORD: ${GMAIL_PASSWORD}
    web:
        image: glitchtip/glitchtip:latest
        depends_on: *default-depends_on
        ports:
            - "8000:8000"
        environment: *default-environment
        restart: unless-stopped
    worker:
        image: glitchtip/glitchtip:latest
        command: celery -A glitchtip worker -B -l INFO
        depends_on: *default-depends_on
        environment: *default-environment
        restart: unless-stopped

volumes:
  data: null
  pg_data: null
